# Generated by Django 3.0.8 on 2020-07-29 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200729_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 13, 46, 5, 177986, tzinfo=utc)),
        ),
    ]
