# Generated by Django 3.0.8 on 2020-08-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200806_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='userartwork',
            name='source',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
