# Generated by Django 3.0.8 on 2020-07-23 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Umetnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_of_birth', models.DateTimeField(verbose_name='birth')),
                ('year_of_death', models.DateTimeField(verbose_name='death')),
                ('nationality', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Umetnina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.DateTimeField(verbose_name='created')),
                ('style', models.CharField(max_length=200)),
                ('technique', models.CharField(max_length=200)),
                ('medium', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Umetnik')),
            ],
        ),
    ]
