# Generated by Django 3.0.8 on 2020-08-26 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arts',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='artwork_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ArtworkLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField()),
                ('artwork_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Arts')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
