# Generated by Django 3.0.8 on 2020-07-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umetnik',
            name='year_of_birth',
            field=models.DateField(verbose_name='birth'),
        ),
        migrations.AlterField(
            model_name='umetnik',
            name='year_of_death',
            field=models.DateField(verbose_name='death'),
        ),
    ]
