# Generated by Django 3.0.8 on 2020-08-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20200826_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtworkLikes',
        ),
    ]
