# Generated by Django 3.0.8 on 2020-07-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20200723_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umetnina',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
