# Generated by Django 3.0.8 on 2020-07-23 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20200723_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umetnina',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
