# Generated by Django 3.0.8 on 2020-08-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20200723_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stili',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stil', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
