# Generated by Django 3.1 on 2020-08-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_arts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='url',
            field=models.URLField(),
        ),
    ]
