# Generated by Django 3.1 on 2020-08-21 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_artworkstags_comments_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkstags',
            name='artwork_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.arts'),
        ),
        migrations.AlterField(
            model_name='artworkstags',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.tags'),
        ),
    ]
