# Generated by Django 3.1 on 2020-08-23 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0012_auto_20200823_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
