"""
Django settings for umetnine project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

FORCE_SCRIPT_NAME = os.environ.get('DJANGO_URL', None)
DB_PORT = os.environ.get('POSTGRES_PORT', 5432)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_+im0gv)g7q$bn781tkxrc^e4$f5)7v&^^_$1w&5hw7kz-9my&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # added
    'crispy_forms',
    'rest_framework',

    # custom
    'artists.apps.ArtistsConfig',
    'account.apps.AccountConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'umetnine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'umetnine.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
# ----> ce zelis uporabljati privzeto bazo sqlite3:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

#with open('user-data.txt', 'r') as data:
#    username, password = data.readline().split()

# ----> PostgreSQL na solskem serverju:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sem2020_tomazd',
        'USER': 'javnost',
        'PASSWORD': 'javnogeslo',
        'HOST': 'baza.fmf.uni-lj.si',
        'PORT': DB_PORT
    }
    
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Belgrade'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

if FORCE_SCRIPT_NAME:
    STATIC_URL = FORCE_SCRIPT_NAME + 'static/'
    LOGIN_REDIRECT_URL = FORCE_SCRIPT_NAME + 'user/profile'
    LOGOUT_REDIRECT_URL = FORCE_SCRIPT_NAME + 'user/logout'
else:
    STATIC_URL = '/static/'
    LOGIN_REDIRECT_URL = '/user/profile'
    LOGOUT_REDIRECT_URL = '/user/logout'

CRISPY_TEMPLATE_PACK = 'bootstrap4'


try:
    from local_settings import *
except ImportError:
    pass
